CREATE DATABASE IF NOT EXISTS tp_database;
USE tp_database;

CREATE TABLE IF NOT EXISTS users(
	id INT AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL,
	password VARCHAR(45) NOT NULL,
	PRIMARY KEY(id)
);

SELECT * FROM users;